modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="mymodpack"
version="1.0.0"
displayName="MyModpack"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="etien, MCreator"

[[dependencies.mymodpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



